### PR TITLE
Support Activerecord 5.2

### PR DESCRIPTION
**Pull request by rapito**
Merge in all other pull requests + missing required changes for type_to_sql

### CODE REVIEW

**Comment by arturtr** [comment]
@ConsultingMD are you going to merge it?

**Comment by hlascelles** [comment]
A gift to 2021... a new gem with this merged @nfoen or @RoryO?

**Comment by RoryO** [comment]
Apologies, I am no longer affiliated with this and have not been for over a year.

**Comment by RoryO** [comment]
Apologies, I am no longer affiliated with this and have not been for over a year. I think @cobbr2 may be able to help find someone who can help.

**Comment by hlascelles** [comment]
@cobbr2 is this something you can help with please?

**Pull request merged**
