### PR TITLE
Unlock dependency for Active Record < 6.0

### PR DESCRIPTION
**Pull request by JuanitoFatas**
Rails 5.1 is released.

How may I run the tests?

### CODE REVIEW

**Comment by RoryO** [comment]
You should be able to run `rake`. I'm unsure if we validated that the tests pass when we converted to AR5.

**Comment by balvig** [comment]
I couldn't get the tests to run, failing on the master branch with:

```
/Users/jens/Documents/activerecord5-redshift-adapter/test/cases/helper.rb:1:in `require': cannot load such file -- /Users/jens/Documents/load_paths (LoadError)
        from /Users/jens/Documents/activerecord5-redshift-adapter/test/cases/helper.rb:1:in `<top (required)>'
        from /Users/jens/Documents/activerecord5-redshift-adapter/test/cases/adapter_test.rb:1:in `require'
        from /Users/jens/Documents/activerecord5-redshift-adapter/test/cases/adapter_test.rb:1:in `<top (required)>'
        from /Users/jens/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/rake_test_loader.rb:15:in `require'
        from /Users/jens/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/rake_test_loader.rb:15:in `block in <main>'
        from /Users/jens/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/rake_test_loader.rb:4:in `select'
        from /Users/jens/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/rake_test_loader.rb:4:in `<main>'
rake aborted!
```

For what it's worth, I did however "manually" test this, and seems to be working fine in Rails 5.1 using @JuanitoFatas' branch 🙏

**Comment by JuanitoFatas** [comment]
I think the tests of this project was [copied from rails](https://github.com/rails/rails/tree/master/activerecord/test), need to copy over again, get it running and fix all failures...

**Comment by RoryO** [comment]
That's likely correct. Thanks for doing this. I don't want to block anyone here. I'll merge and push up another gem. As always help fixing the tests is much welcomed. We're a bit backlogged at the moment.

**Comment by aamine** [comment]
Really nice, thanks!!
Could you kindly push activerecord5-redshift-adapter gem to rubygems.org?

**Comment by aamine** [comment]
I see gem is pushed! Thanks a lot!!!

**Pull request merged**
